/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ContaIndexRouteImport } from './routes/conta.index'
import { Route as ViagemSlugRouteImport } from './routes/viagem.$slug'
import { Route as ReservaConfirmadaSlugRouteImport } from './routes/reserva-confirmada.$slug'
import { Route as DashboardPassageirosRouteImport } from './routes/dashboard.passageiros'
import { Route as ContaVouchersRouteImport } from './routes/conta.vouchers'
import { Route as ContaViagensRouteImport } from './routes/conta.viagens'
import { Route as ContaRifasRouteImport } from './routes/conta.rifas'
import { Route as ContaDescontosRouteImport } from './routes/conta.descontos'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as AgenciaSlugRouteImport } from './routes/agencia.$slug'
import { Route as DashboardViagensIndexRouteImport } from './routes/dashboard.viagens.index'
import { Route as DashboardViagensNovaRouteImport } from './routes/dashboard.viagens.nova'
import { Route as DashboardViagensTripIdRouteImport } from './routes/dashboard.viagens.$tripId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContaRoute,
} as any)
const ViagemSlugRoute = ViagemSlugRouteImport.update({
  id: '/viagem/$slug',
  path: '/viagem/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaConfirmadaSlugRoute = ReservaConfirmadaSlugRouteImport.update({
  id: '/reserva-confirmada/$slug',
  path: '/reserva-confirmada/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPassageirosRoute = DashboardPassageirosRouteImport.update({
  id: '/passageiros',
  path: '/passageiros',
  getParentRoute: () => DashboardRoute,
} as any)
const ContaVouchersRoute = ContaVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => ContaRoute,
} as any)
const ContaViagensRoute = ContaViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => ContaRoute,
} as any)
const ContaRifasRoute = ContaRifasRouteImport.update({
  id: '/rifas',
  path: '/rifas',
  getParentRoute: () => ContaRoute,
} as any)
const ContaDescontosRoute = ContaDescontosRouteImport.update({
  id: '/descontos',
  path: '/descontos',
  getParentRoute: () => ContaRoute,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciaSlugRoute = AgenciaSlugRouteImport.update({
  id: '/agencia/$slug',
  path: '/agencia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardViagensIndexRoute = DashboardViagensIndexRouteImport.update({
  id: '/viagens/',
  path: '/viagens/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardViagensNovaRoute = DashboardViagensNovaRouteImport.update({
  id: '/viagens/nova',
  path: '/viagens/nova',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardViagensTripIdRoute = DashboardViagensTripIdRouteImport.update({
  id: '/viagens/$tripId',
  path: '/viagens/$tripId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta': typeof ContaRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/agencia/$slug': typeof AgenciaSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/conta/descontos': typeof ContaDescontosRoute
  '/conta/rifas': typeof ContaRifasRoute
  '/conta/viagens': typeof ContaViagensRoute
  '/conta/vouchers': typeof ContaVouchersRoute
  '/dashboard/passageiros': typeof DashboardPassageirosRoute
  '/reserva-confirmada/$slug': typeof ReservaConfirmadaSlugRoute
  '/viagem/$slug': typeof ViagemSlugRoute
  '/conta/': typeof ContaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/viagens/$tripId': typeof DashboardViagensTripIdRoute
  '/dashboard/viagens/nova': typeof DashboardViagensNovaRoute
  '/dashboard/viagens/': typeof DashboardViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencia/$slug': typeof AgenciaSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/conta/descontos': typeof ContaDescontosRoute
  '/conta/rifas': typeof ContaRifasRoute
  '/conta/viagens': typeof ContaViagensRoute
  '/conta/vouchers': typeof ContaVouchersRoute
  '/dashboard/passageiros': typeof DashboardPassageirosRoute
  '/reserva-confirmada/$slug': typeof ReservaConfirmadaSlugRoute
  '/viagem/$slug': typeof ViagemSlugRoute
  '/conta': typeof ContaIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/viagens/$tripId': typeof DashboardViagensTripIdRoute
  '/dashboard/viagens/nova': typeof DashboardViagensNovaRoute
  '/dashboard/viagens': typeof DashboardViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta': typeof ContaRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/agencia/$slug': typeof AgenciaSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/conta/descontos': typeof ContaDescontosRoute
  '/conta/rifas': typeof ContaRifasRoute
  '/conta/viagens': typeof ContaViagensRoute
  '/conta/vouchers': typeof ContaVouchersRoute
  '/dashboard/passageiros': typeof DashboardPassageirosRoute
  '/reserva-confirmada/$slug': typeof ReservaConfirmadaSlugRoute
  '/viagem/$slug': typeof ViagemSlugRoute
  '/conta/': typeof ContaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/viagens/$tripId': typeof DashboardViagensTripIdRoute
  '/dashboard/viagens/nova': typeof DashboardViagensNovaRoute
  '/dashboard/viagens/': typeof DashboardViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conta'
    | '/dashboard'
    | '/agencia/$slug'
    | '/checkout/$slug'
    | '/conta/descontos'
    | '/conta/rifas'
    | '/conta/viagens'
    | '/conta/vouchers'
    | '/dashboard/passageiros'
    | '/reserva-confirmada/$slug'
    | '/viagem/$slug'
    | '/conta/'
    | '/dashboard/'
    | '/dashboard/viagens/$tripId'
    | '/dashboard/viagens/nova'
    | '/dashboard/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencia/$slug'
    | '/checkout/$slug'
    | '/conta/descontos'
    | '/conta/rifas'
    | '/conta/viagens'
    | '/conta/vouchers'
    | '/dashboard/passageiros'
    | '/reserva-confirmada/$slug'
    | '/viagem/$slug'
    | '/conta'
    | '/dashboard'
    | '/dashboard/viagens/$tripId'
    | '/dashboard/viagens/nova'
    | '/dashboard/viagens'
  id:
    | '__root__'
    | '/'
    | '/conta'
    | '/dashboard'
    | '/agencia/$slug'
    | '/checkout/$slug'
    | '/conta/descontos'
    | '/conta/rifas'
    | '/conta/viagens'
    | '/conta/vouchers'
    | '/dashboard/passageiros'
    | '/reserva-confirmada/$slug'
    | '/viagem/$slug'
    | '/conta/'
    | '/dashboard/'
    | '/dashboard/viagens/$tripId'
    | '/dashboard/viagens/nova'
    | '/dashboard/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaRoute: typeof ContaRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AgenciaSlugRoute: typeof AgenciaSlugRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  ReservaConfirmadaSlugRoute: typeof ReservaConfirmadaSlugRoute
  ViagemSlugRoute: typeof ViagemSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/conta/': {
      id: '/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof ContaRoute
    }
    '/viagem/$slug': {
      id: '/viagem/$slug'
      path: '/viagem/$slug'
      fullPath: '/viagem/$slug'
      preLoaderRoute: typeof ViagemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva-confirmada/$slug': {
      id: '/reserva-confirmada/$slug'
      path: '/reserva-confirmada/$slug'
      fullPath: '/reserva-confirmada/$slug'
      preLoaderRoute: typeof ReservaConfirmadaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/passageiros': {
      id: '/dashboard/passageiros'
      path: '/passageiros'
      fullPath: '/dashboard/passageiros'
      preLoaderRoute: typeof DashboardPassageirosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/conta/vouchers': {
      id: '/conta/vouchers'
      path: '/vouchers'
      fullPath: '/conta/vouchers'
      preLoaderRoute: typeof ContaVouchersRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/viagens': {
      id: '/conta/viagens'
      path: '/viagens'
      fullPath: '/conta/viagens'
      preLoaderRoute: typeof ContaViagensRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/rifas': {
      id: '/conta/rifas'
      path: '/rifas'
      fullPath: '/conta/rifas'
      preLoaderRoute: typeof ContaRifasRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/descontos': {
      id: '/conta/descontos'
      path: '/descontos'
      fullPath: '/conta/descontos'
      preLoaderRoute: typeof ContaDescontosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencia/$slug': {
      id: '/agencia/$slug'
      path: '/agencia/$slug'
      fullPath: '/agencia/$slug'
      preLoaderRoute: typeof AgenciaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/viagens/': {
      id: '/dashboard/viagens/'
      path: '/viagens'
      fullPath: '/dashboard/viagens/'
      preLoaderRoute: typeof DashboardViagensIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/viagens/nova': {
      id: '/dashboard/viagens/nova'
      path: '/viagens/nova'
      fullPath: '/dashboard/viagens/nova'
      preLoaderRoute: typeof DashboardViagensNovaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/viagens/$tripId': {
      id: '/dashboard/viagens/$tripId'
      path: '/viagens/$tripId'
      fullPath: '/dashboard/viagens/$tripId'
      preLoaderRoute: typeof DashboardViagensTripIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface ContaRouteChildren {
  ContaDescontosRoute: typeof ContaDescontosRoute
  ContaRifasRoute: typeof ContaRifasRoute
  ContaViagensRoute: typeof ContaViagensRoute
  ContaVouchersRoute: typeof ContaVouchersRoute
  ContaIndexRoute: typeof ContaIndexRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaDescontosRoute: ContaDescontosRoute,
  ContaRifasRoute: ContaRifasRoute,
  ContaViagensRoute: ContaViagensRoute,
  ContaVouchersRoute: ContaVouchersRoute,
  ContaIndexRoute: ContaIndexRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

interface DashboardRouteChildren {
  DashboardPassageirosRoute: typeof DashboardPassageirosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardViagensTripIdRoute: typeof DashboardViagensTripIdRoute
  DashboardViagensNovaRoute: typeof DashboardViagensNovaRoute
  DashboardViagensIndexRoute: typeof DashboardViagensIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPassageirosRoute: DashboardPassageirosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardViagensTripIdRoute: DashboardViagensTripIdRoute,
  DashboardViagensNovaRoute: DashboardViagensNovaRoute,
  DashboardViagensIndexRoute: DashboardViagensIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaRoute: ContaRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AgenciaSlugRoute: AgenciaSlugRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  ReservaConfirmadaSlugRoute: ReservaConfirmadaSlugRoute,
  ViagemSlugRoute: ViagemSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
